const FrasesBiscoito = [
    "A sorte está a seu favor hoje.",
    "Grandes oportunidades estão a caminho.",
    "Seu sorriso iluminará o dia de alguém.",
    "Acredite em si mesmo e tudo será possível.",
    "A sorte favorece os corajosos.",
    "Você aprenderá algo novo a cada dia.",
    "A paciência é uma virtude.",
    "Siga seus sonhos com determinação.",
    "A vida é o que fazemos dela.",
    "Aja agora, não espere.",
    "Grandes coisas estão por vir.",
    "Mantenha uma atitude positiva.",
    "A gratidão transforma o comum em extraordinário.",
    "Nada é impossível para um coração determinado.",
    "As melhores coisas da vida são gratuitas.",
    "Sorria para o mundo e o mundo sorrirá de volta.",
    "Siga seu coração, ele conhece o caminho.",
    "A persistência leva ao sucesso.",
    "Boas coisas acontecem para aqueles que esperam.",
    "Hoje é o primeiro dia do resto de sua vida.",
    "Faça o que você ama, ame o que você faz.",
    "A simplicidade é a chave da felicidade.",
    "Aprenda com o passado, viva no presente, sonhe com o futuro.",
    "A verdadeira sabedoria está em reconhecer a própria ignorância.",
    "Seja gentil, pois todos estão lutando uma batalha que você não conhece.",
    "A vida é feita de momentos, aproveite cada um deles.",
    "Você é mais forte do que pensa.",
    "O que você faz hoje pode melhorar todos os seus amanhãs.",
    "Acredite em milagres.",
    "Tudo o que você pode imaginar é real."
];

export default FrasesBiscoito

